In [1]:
import numpy as np

# 1. Definimos una matriz cuadrada (en este caso, 3x3)
A = np.array([
    [4, 2, 0], 
    [2, 4, 1], 
    [0, 1, 3]
])

print("Matriz A:")
print(A)
print("-" * 30)

# 2. Usamos la función eig() del submódulo linalg (Linear Algebra) de numpy
valores_propios, vectores_propios = np.linalg.eig(A)

# 3. Mostramos los resultados
print("Valores propios (Eigenvalues):")
print(valores_propios)
print("-" * 30)

print("Vectores propios (Eigenvectors):")
print(vectores_propios)
print("-" * 30)

# 4. Comprobación matemática (A * v = lambda * v)
# Tomamos el primer valor propio y su vector propio (primera columna)
lambda_1 = valores_propios[0]
v_1 = vectores_propios[:, 0]

# Multiplicamos la matriz A por el vector propio v_1 (producto punto)
izq = np.dot(A, v_1)

# Multiplicamos el valor propio escalar por el vector v_1
der = lambda_1 * v_1

print("Comprobación (A * v_1):", izq)
print("Comprobación (lambda_1 * v_1):", der)

Matriz A:
[[4 2 0]
 [2 4 1]
 [0 1 3]]
------------------------------
Valores propios (Eigenvalues):
[6.16424794 1.60861762 3.22713444]
------------------------------
Vectores propios (Eigenvectors):
[[-0.6611152   0.56181831 -0.49727948]
 [-0.7154086  -0.6717612   0.19216509]
 [-0.2260912   0.48280128  0.84604119]]
------------------------------
Comprobación (A * v_1): [-4.07527799 -4.409956   -1.39368219]
Comprobación (lambda_1 * v_1): [-4.07527799 -4.409956   -1.39368219]
